<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $admins = [
            'admin_hash_id' => md5(uniqid(rand(), true)),
            'dept_id' => 0, // Adjust this value based on your needs
            'name' => 'Admin User',
            'email' => 'admin@email.com', // Change this email address
            'password' => Hash::make(1234), // Change this password
            'verify' => 1, // Set to 1 if you want to mark the email as verified
            'remember_token' => '',
            'created_at' => now(),
            'updated_at' => now(),
            'pin' => 102, // Adjust this if needed
            'user_status' => 1, // Set to 1 if you want to mark the user as active
        ];

        DB::table('admins')->insert($admins);

        DB::table('web_settings')->insert([
            'school_title' => 'Your School Title',
            'logo' => 'logo.png',
            'phone1' => '1234567890',
            'phone2' => null,
            'fax' => null,
            'email' => 'school@example.com',
            'address_one' => '123 Street, City',
            'address_two' => null,
            'eiin' => null,
            'facebook' => null,
            'twitter' => null,
            'linkedin' => null,
            'instagram' => null,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        DB::table('histories')->insert([
            'history' => 'Your history description goes here',
            'dept_id' => 0, // Assuming default value is 0
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        DB::table('event_types')->insert([
            'type_name' => 'Academic',
            'color' => '#ebebeb', // Example color value
            'status' => 1, // Example status value
            'dept_id' => 0, // Assuming default value is 0
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        DB::table('faculties')->insert([
            [
                'faculty_hash_id' => Str::uuid(),
                'faculty_name' => 'ব্যবসা প্রশাসন অনুযদ',
                'faculty_slug' => 'business-administration',
                'faculty_status' => 1,
                'created_at' => '2024-03-20 12:15:41',
                'updated_at' => '2024-03-20 12:15:41',
            ],
            [
                'faculty_hash_id' => Str::uuid(),
                'faculty_name' => 'কলা অনুযদ',
                'faculty_slug' => 'arts',
                'faculty_status' => 1,
                'created_at' => '2024-03-20 12:16:17',
                'updated_at' => '2024-03-20 12:16:17',
            ],
            [
                'faculty_hash_id' => Str::uuid(),
                'faculty_name' => 'বিজ্ঞান অনুযদ',
                'faculty_slug' => 'science',
                'faculty_status' => 1,
                'created_at' => '2024-03-20 12:17:03',
                'updated_at' => '2024-03-20 12:17:03',
            ],
            [
                'faculty_hash_id' => Str::uuid(),
                'faculty_name' => 'সমাজ বিজ্ঞান অনুযদ',
                'faculty_slug' => 'social-science',
                'faculty_status' => 1,
                'created_at' => '2024-03-20 12:17:42',
                'updated_at' => '2024-03-20 12:17:42',
            ],
        ]);

        // Seed departments table
        DB::table('departments')->insert([
            [
                'faculty_id' => 1,
                'department_hash_id' => Str::uuid(),
                'department_name' => 'হিসাব বিজ্ঞান',
                'department_slug' => 'accounting',
                'department_status' => 1,
                'created_at' => '2024-03-20 11:44:09',
                'updated_at' => '2024-03-20 11:44:09',
            ],
            [
                'faculty_id' => 1,
                'department_hash_id' => Str::uuid(),
                'department_name' => 'ফিন্যান্স ও ব্যাংকিং',
                'department_slug' => 'finance-and-banking',
                'department_status' => 1,
                'created_at' => '2024-03-20 11:44:51',
                'updated_at' => '2024-03-20 11:44:51',
            ],
            [
                'faculty_id' => 1,
                'department_hash_id' => Str::uuid(),
                'department_name' => 'মার্কেটিং',
                'department_slug' => 'marketing',
                'department_status' => 1,
                'created_at' => '2024-03-20 11:45:15',
                'updated_at' => '2024-03-20 11:45:15',
            ],
            [
                'faculty_id' => 1,
                'department_hash_id' => Str::uuid(),
                'department_name' => 'ব্যবস্থাপনা',
                'department_slug' => 'management',
                'department_status' => 1,
                'created_at' => '2024-03-20 11:45:57',
                'updated_at' => '2024-03-20 11:45:57',
            ],
            [
                'faculty_id' => 2,
                'department_hash_id' => Str::uuid(),
                'department_name' => 'বাংলা',
                'department_slug' => 'bengali',
                'department_status' => 1,
                'created_at' => '2024-03-20 11:46:21',
                'updated_at' => '2024-03-20 11:46:21',
            ],
            [
                'faculty_id' => 2,
                'department_hash_id' => Str::uuid(),
                'department_name' => 'ইংলিশ',
                'department_slug' => 'english',
                'department_status' => 1,
                'created_at' => '2024-03-20 11:46:39',
                'updated_at' => '2024-03-20 11:46:39',
            ],
            [
                'faculty_id' => 2,
                'department_hash_id' => Str::uuid(),
                'department_name' => 'ইতিহাস',
                'department_slug' => 'history',
                'department_status' => 1,
                'created_at' => '2024-03-20 11:46:59',
                'updated_at' => '2024-03-20 11:46:59',
            ],
            [
                'faculty_id' => 2,
                'department_hash_id' => Str::uuid(),
                'department_name' => 'ইসলামের ইতিহাস ও সংস্কৃতি',
                'department_slug' => 'islamic-history-and-culture',
                'department_status' => 1,
                'created_at' => '2024-03-20 11:47:56',
                'updated_at' => '2024-03-20 11:47:56',
            ],
            [
                'faculty_id' => 2,
                'department_hash_id' => Str::uuid(),
                'department_name' => 'ইসলামী শিক্ষা',
                'department_slug' => 'islamic-education',
                'department_status' => 1,
                'created_at' => '2024-03-20 11:48:27',
                'updated_at' => '2024-03-20 11:48:27',
            ],
            [
                'faculty_id' => 2,
                'department_hash_id' => Str::uuid(),
                'department_name' => 'দর্শন',
                'department_slug' => 'philosophy',
                'department_status' => 1,
                'created_at' => '2024-03-20 11:48:48',
                'updated_at' => '2024-03-20 11:48:48',
            ],
            [
                'faculty_id' => 3,
                'department_hash_id' => Str::uuid(),
                'department_name' => 'পদার্থবিদ্যা',
                'department_slug' => 'physics',
                'department_status' => 1,
                'created_at' => '2024-03-20 11:50:10',
                'updated_at' => '2024-03-20 11:50:10',
            ],
            [
                'faculty_id' => 3,
                'department_hash_id' => Str::uuid(),
                'department_name' => 'রসায়ন',
                'department_slug' => 'chemistry',
                'department_status' => 1,
                'created_at' => '2024-03-20 11:50:28',
                'updated_at' => '2024-03-20 11:50:28',
            ],
            [
                'faculty_id' => 3,
                'department_hash_id' => Str::uuid(),
                'department_name' => 'গণিত',
                'department_slug' => 'mathematics',
                'department_status' => 1,
                'created_at' => '2024-03-20 11:50:51',
                'updated_at' => '2024-03-20 11:50:51',
            ],
            [
                'faculty_id' => 3,
                'department_hash_id' => Str::uuid(),
                'department_name' => 'উদ্ভিদ বিজ্ঞান',
                'department_slug' => 'botany',
                'department_status' => 1,
                'created_at' => '2024-03-20 11:51:32',
                'updated_at' => '2024-03-20 11:51:32',
            ],
            [
                'faculty_id' => 3,
                'department_hash_id' => Str::uuid(),
                'department_name' => 'প্রানীবিদ্যা',
                'department_slug' => 'zoology',
                'department_status' => 1,
                'created_at' => '2024-03-20 11:52:01',
                'updated_at' => '2024-03-20 11:52:01',
            ],
            [
                'faculty_id' => 3,
                'department_hash_id' => Str::uuid(),
                'department_name' => 'তথ্য ও যোগাযোগ প্রযুক্তি',
                'department_slug' => 'information-and-communication-technology',
                'department_status' => 1,
                'created_at' => '2024-03-20 11:52:58',
                'updated_at' => '2024-03-20 11:52:58',
            ],
            [
                'faculty_id' => 3,
                'department_hash_id' => Str::uuid(),
                'department_name' => 'ভূগোল ও পরিবেশ',
                'department_slug' => 'geography-and-environment',
                'department_status' => 1,
                'created_at' => '2024-03-20 11:53:31',
                'updated_at' => '2024-03-20 11:53:31',
            ],
            [
                'faculty_id' => 4,
                'department_hash_id' => Str::uuid(),
                'department_name' => 'সমাজ বিজ্ঞান',
                'department_slug' => 'social-science',
                'department_status' => 1,
                'created_at' => '2024-03-20 11:55:01',
                'updated_at' => '2024-03-20 11:55:01',
            ],
            [
                'faculty_id' => 4,
                'department_hash_id' => Str::uuid(),
                'department_name' => 'অর্থনীতি',
                'department_slug' => 'economics',
                'department_status' => 1,
                'created_at' => '2024-03-20 11:56:02',
                'updated_at' => '2024-03-20 11:56:02',
            ],
            [
                'faculty_id' => 4,
                'department_hash_id' => Str::uuid(),
                'department_name' => 'রাষ্ট্রবিজ্ঞান',
                'department_slug' => 'political-science',
                'department_status' => 1,
                'created_at' => '2024-03-20 11:56:42',
                'updated_at' => '2024-03-20 11:56:42',
            ],
            [
                'faculty_id' => 4,
                'department_hash_id' => Str::uuid(),
                'department_name' => 'সমাজকর্ম',
                'department_slug' => 'social-work',
                'department_status' => 1,
                'created_at' => '2024-03-20 11:57:04',
                'updated_at' => '2024-03-20 11:57:04',
            ],
        ]);
        

        DB::table('menus')->insert([
            [
                'menu_name' => 'প্রতিষ্ঠান সম্পর্কে',
                'menu_slug' => 'about-institute',
                'menu_desc' => '',
                'upload' => '',
                'menu_status' => 1,
                'is_home' => 0,
                'dept_id' => 0, // Replace 1 with the actual department ID
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'menu_name' => 'পাঠ্যক্রম সম্পর্কে',
                'menu_slug' => 'about-curriculam',
                'menu_desc' => '',
                'upload' => '',
                'menu_status' => 1,
                'is_home' => 0,
                'dept_id' => 0, // Replace 1 with the actual department ID
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_name' => 'সহশিক্ষা কার্যক্রম',
                'menu_slug' => 'cocurricular-activities',
                'menu_desc' => '',
                'upload' => '',
                'menu_status' => 1,
                'is_home' => 0,
                'dept_id' => 0, // Replace 1 with the actual department ID
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_name' => 'ই-সেবা',
                'menu_slug' => 'e-help',
                'menu_desc' => '',
                'upload' => '',
                'menu_status' => 1,
                'is_home' => 0,
                'dept_id' => 0, // Replace 1 with the actual department ID
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_name' => 'অনলাইন এডমিশন',
                'menu_slug' => 'online-admission',
                'menu_desc' => '',
                'upload' => '',
                'menu_status' => 1,
                'is_home' => 0,
                'dept_id' => 0, // Replace 1 with the actual department ID
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Add more menu data here as needed

            [
                'menu_name' => 'আমাদের কলেজ',
                'menu_slug' => 'our-college',
                'menu_desc' => '',
                'upload' => '1710349711.png',
                'menu_status' => 1,
                'is_home' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-13 17:08:31',
                'updated_at' => '2024-03-13 17:08:31',
            ],
            [
                'menu_name' => 'প্রশাসন',
                'menu_slug' => 'prsasn',
                'menu_desc' => '',
                'upload' => '',
                'menu_status' => 1,
                'is_home' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-12 11:58:25',
                'updated_at' => '2024-03-12 11:58:25',
            ],
            [
                'menu_name' => 'অনুষদ',
                'menu_slug' => 'onushd',
                'menu_desc' => '',
                'upload' => '',
                'menu_status' => 1,
                'is_home' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-12 11:59:42',
                'updated_at' => '2024-03-12 11:59:42',
            ],
            [
                'menu_name' => 'পরীক্ষা ও ফলাফল',
                'menu_slug' => 'preeksha-oo-flafl',
                'menu_desc' => '',
                'upload' => '',
                'menu_status' => 1,
                'is_home' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-12 12:00:18',
                'updated_at' => '2024-03-12 12:00:18',
            ],
            [
                'menu_name' => 'ভর্তি বিষয়ক',
                'menu_slug' => 'vrti-bishyk',
                'menu_desc' => '',
                'upload' => '',
                'menu_status' => 1,
                'is_home' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-12 12:01:35',
                'updated_at' => '2024-03-12 12:01:35',
            ],
            [
                'menu_name' => 'সংগঠন',
                'menu_slug' => 'snggthn',
                'menu_desc' => '',
                'upload' => '',
                'menu_status' => 1,
                'is_home' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-12 12:02:37',
                'updated_at' => '2024-03-12 12:02:37',
            ],

            [
                'menu_name' => 'অভিযোগ প্রতিকার ব্যবস্থাপনা',
                'menu_slug' => 'ovizog-prtikar-lingk',
                'menu_desc' => '',
                'upload' => '',
                'menu_status' => 1,
                'is_home' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-12 12:03:56',
                'updated_at' => '2024-03-12 12:04:43',
            ],
            [
                'menu_name' => 'বার্যিক কর্মপরিকল্পনা',
                'menu_slug' => 'barzik-krmpriklpna',
                'menu_desc' => '',
                'upload' => '',
                'menu_status' => 1,
                'is_home' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-12 12:07:04',
                'updated_at' => '2024-03-12 12:07:04',
            ],
            [
                'menu_name' => 'এলামনাই সেল',
                'menu_slug' => 'elamnai-sel',
                'menu_desc' => '',
                'upload' => '',
                'menu_status' => 1,
                'is_home' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-12 12:07:40',
                'updated_at' => '2024-03-12 12:07:40',
            ],
        ]);

        DB::table('sub_menus')->insert([
            [
                'menu_id' => 1, // Replace with the actual menu ID
                'submenu_name' => 'প্রতিষ্ঠান সম্পর্কে',
                'submenu_slug' => 'about-institution',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 1, // Replace with the actual menu ID
                'submenu_name' => 'প্রশাসন',
                'submenu_slug' => 'administration',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 1, // Replace with the actual menu ID
                'submenu_name' => 'শিক্ষক-কর্মকর্তা-কর্মচারী',
                'submenu_slug' => 'teachers-and-staffs',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'menu_id' => 2, // Replace with the actual menu ID
                'submenu_name' => 'স্তর ও বিভাগ সমুহ',
                'submenu_slug' => 'hierarchy',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 2, // Replace with the actual menu ID
                'submenu_name' => 'ভর্তি সংক্রান্ত',
                'submenu_slug' => 'about-admission',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 2, // Replace with the actual menu ID
                'submenu_name' => 'পরিক্ষা সংক্রান্ত',
                'submenu_slug' => 'about-exam',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 2, // Replace with the actual menu ID
                'submenu_name' => 'ফলাফল সংক্রান্ত',
                'submenu_slug' => 'about-result',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 3, // Replace with the actual menu ID
                'submenu_name' => 'লাইব্রেরি ও ক্লাব',
                'submenu_slug' => 'library-and-club',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 3, // Replace with the actual menu ID
                'submenu_name' => 'কো-কারিকুলাম',
                'submenu_slug' => 'co-curriculam',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 3, // Replace with the actual menu ID
                'submenu_name' => 'এক্সট্রা-কারিকুলাম',
                'submenu_slug' => 'extra-curriculam',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 3, // Replace with the actual menu ID
                'submenu_name' => 'হোস্টেল',
                'submenu_slug' => 'dormitory',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 4, // Replace with the actual menu ID
                'submenu_name' => 'ই পেমেন্ট সংক্রান্ত সেবা',
                'submenu_slug' => 'e-payment',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 4, // Replace with the actual menu ID
                'submenu_name' => 'পেমেন্ট রশিদ সার্চ',
                'submenu_slug' => 'search-payment-receipt',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 4, // Replace with the actual menu ID
                'submenu_name' => 'পরিক্ষার ফলাফল',
                'submenu_slug' => 'result',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 4, // Replace with the actual menu ID
                'submenu_name' => 'মোবাইল  App',
                'submenu_slug' => 'mobile-app',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Add more submenu data here as needed.
            [
                'menu_id' => 6,
                'submenu_name' => 'সাফল্য ও অর্জন',
                'submenu_slug' => 'success-and-achievement',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 6,
                'submenu_name' => 'এক নজরে',
                'submenu_slug' => 'at-a-glance',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 6,
                'submenu_name' => 'অধ্যক্ষ',
                'submenu_slug' => 'chairman',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 6,
                'submenu_name' => 'লক্ষ্য ও উদ্দেশ্য',
                'submenu_slug' => 'goals-and-objectives',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'menu_id' => 7,
                'submenu_name' => 'প্রশাসনিক বিজ্ঞপ্তি',
                'submenu_slug' => 'administrative-notices',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 7,
                'submenu_name' => 'পরিষদ সমুহ',
                'submenu_slug' => 'committees',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 7,
                'submenu_name' => 'প্রশাসনিক কাঠামো',
                'submenu_slug' => 'administrative-structure',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 7,
                'submenu_name' => 'অফিস স্টাফ',
                'submenu_slug' => 'office-staff',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'menu_id' => 8,
                'submenu_name' => 'নিতিমালা',
                'submenu_slug' => 'policies',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 8,
                'submenu_name' => 'কর্ম পরিকল্পনা',
                'submenu_slug' => 'work-plans',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 8,
                'submenu_name' => 'বিভাগীয় প্রধানগণ',
                'submenu_slug' => 'department-heads',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 8,
                'submenu_name' => 'অনুষদ ভিত্তিক বিভাগ সমুহ',
                'submenu_slug' => 'section-based-departments',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 9,
                'submenu_name' => 'সার্টিফিকেট সংক্রান্ত',
                'submenu_slug' => 'certificate-related',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 9,
                'submenu_name' => 'ফলাফল সমুহ',
                'submenu_slug' => 'result-lists',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 9,
                'submenu_name' => 'পরিক্ষা নিয়ন্ত্রকের অফিস',
                'submenu_slug' => 'exam-controller-office',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 9,
                'submenu_name' => 'পরিক্ষার তালিকা',
                'submenu_slug' => 'exam-schedule',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 10,
                'submenu_name' => 'ফোকাল পয়েন্ট',
                'submenu_slug' => 'focal-point',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 10,
                'submenu_name' => 'ভর্তি পরিক্ষার ফলাফল',
                'submenu_slug' => 'admission-exam-results',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 10,
                'submenu_name' => 'ভর্তি ফর্ম',
                'submenu_slug' => 'admission-form',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 10,
                'submenu_name' => 'ভর্তি বিষয়ক তথ্য',
                'submenu_slug' => 'admission-information',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 11,
                'submenu_name' => 'ক্লাব সমুহ',
                'submenu_slug' => 'clubs',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 11,
                'submenu_name' => 'শিক্ষক ছাত্র কল্যান সমিতি',
                'submenu_slug' => 'teacher-student-welfare-committee',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 11,
                'submenu_name' => 'বিএন্সিসি',
                'submenu_slug' => 'bncc',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 11,
                'submenu_name' => 'রোবার',
                'submenu_slug' => 'robur',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 12,
                'submenu_name' => 'নির্দেশিকাসমুহ',
                'submenu_slug' => 'directories',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 12,
                'submenu_name' => 'অনলাইন অভিযোগ দাখিল',
                'submenu_slug' => 'submit-online-complaint',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 12,
                'submenu_name' => 'অভিযোগ প্রতিকার ব্যবস্থা',
                'submenu_slug' => 'complaint-resolution-mechanism',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 12,
                'submenu_name' => 'অনিক ও আপিল কর্মকর্তা',
                'submenu_slug' => 'appellate-officer',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 13,
                'submenu_name' => 'কর্মপরিকল্পনা',
                'submenu_slug' => 'work-plan',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 13,
                'submenu_name' => 'ত্রৈমাসিক অর্জন',
                'submenu_slug' => 'quarterly-earnings',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 13,
                'submenu_name' => 'উদ্যোগ সমুহ',
                'submenu_slug' => 'initiatives',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 13,
                'submenu_name' => 'প্রকিউরমেন্ট আইন ও বিধিমালা',
                'submenu_slug' => 'procurement-law-and-regulations',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 14,
                'submenu_name' => 'এলামনাই এসোসিয়েশন সংক্রান্ত তথ্য',
                'submenu_slug' => 'alumni-association-info',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 14,
                'submenu_name' => 'এলামনাই আইন ও বিধিমালা',
                'submenu_slug' => 'alumni-law-and-regulations',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 14,
                'submenu_name' => 'এলামনাই তালিকা',
                'submenu_slug' => 'alumni-list',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'menu_id' => 14,
                'submenu_name' => 'ফোকাল পয়েন্ট তথ্য',
                'submenu_slug' => 'focal-point-info',
                'submenu_desc' => '',
                'upload' => '',
                'dept_id' => 0, // Replace with the actual department ID
                'submenu_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);

        DB::table('child_menus')->insert([
            [
                'menu_id' => 1,
                'submenu_id' => 1,
                'childmenu_name' => 'পঠভূমি ও ইতিহাস',
                'child_menu_slug' => 'pthvuumi-oo-itihas',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-18 12:11:44',
                'updated_at' => '2024-03-18 12:11:44',
            ],
            [
                'menu_id' => 1,
                'submenu_id' => 1,
                'childmenu_name' => 'এক নজরে',
                'child_menu_slug' => 'ek-njre',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-18 12:10:38',
                'updated_at' => '2024-03-18 12:10:38',
            ],
            [
                'menu_id' => 1,
                'submenu_id' => 1,
                'childmenu_name' => 'ভিশন ও মিশন',
                'child_menu_slug' => 'visn-oo-misn',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-18 12:12:14',
                'updated_at' => '2024-03-18 12:12:14',
            ],
            [
                'menu_id' => 1,
                'submenu_id' => 1,
                'childmenu_name' => 'অবকাঠামোর তথ্য',
                'child_menu_slug' => 'obkathamor-tthz',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-18 12:13:00',
                'updated_at' => '2024-03-18 12:13:00',
            ],
            [
                'menu_id' => 1,
                'submenu_id' => 1,
                'childmenu_name' => 'জনবল কাঠামো',
                'child_menu_slug' => 'jnbl-kathamo',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-18 12:13:36',
                'updated_at' => '2024-03-18 12:13:36',
            ],
            [
                'menu_id' => 1,
                'submenu_id' => 1,
                'childmenu_name' => 'সুবিধা সমুহ',
                'child_menu_slug' => 'subidha-smuh',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-18 12:14:11',
                'updated_at' => '2024-03-18 12:14:11',
            ],
            [
                'menu_id' => 1,
                'submenu_id' => 1,
                'childmenu_name' => 'সাফল্য সমুহ',
                'child_menu_slug' => 'saflz-smuh',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-18 12:14:43',
                'updated_at' => '2024-03-18 12:14:43',
            ],
            [
                'menu_id' => 1,
                'submenu_id' => 2,
                'childmenu_name' => 'অধ্যক্ষ',
                'child_menu_slug' => 'odhzksh',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-18 12:15:23',
                'updated_at' => '2024-03-18 12:15:23',
            ],
            [
                'menu_id' => 1,
                'submenu_id' => 2,
                'childmenu_name' => 'উপাধ্যক্ষ',
                'child_menu_slug' => 'upadhzksh',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-18 12:16:06',
                'updated_at' => '2024-03-18 12:16:06',
            ],
            [
                'menu_id' => 1,
                'submenu_id' => 2,
                'childmenu_name' => 'প্রাপ্তন অধ্যক্ষ বৃন্দ',
                'child_menu_slug' => 'praptn-odhzksh-brrind',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-18 12:18:06',
                'updated_at' => '2024-03-18 12:18:06',
            ],
            [
                'menu_id' => 1,
                'submenu_id' => 2,
                'childmenu_name' => 'প্রাক্তন উপাধ্যক্ষ বৃন্দ',
                'child_menu_slug' => 'praktn-upadhzksh-brrind',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-18 12:19:45',
                'updated_at' => '2024-03-18 12:19:45',
            ],
            [
                'menu_id' => 1,
                'submenu_id' => 2,
                'childmenu_name' => 'একাডেমিক কাউন্সিল',
                'child_menu_slug' => 'ekademik-kaunsil',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-18 12:20:52',
                'updated_at' => '2024-03-18 12:20:52',
            ],
            [
                'menu_id' => 1,
                'submenu_id' => 2,
                'childmenu_name' => 'শিক্ষক পরিষদ',
                'child_menu_slug' => 'sikshk-prishd',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-18 12:21:49',
                'updated_at' => '2024-03-18 12:21:49',
            ],
            [
                'menu_id' => 1,
                'submenu_id' => 2,
                'childmenu_name' => 'বিভিন্ন কমিটি',
                'child_menu_slug' => 'bivinn-kmiti',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-18 12:22:30',
                'updated_at' => '2024-03-18 12:22:30',
            ],
            [
                'menu_id' => 1,
                'submenu_id' => 3,
                'childmenu_name' => 'শিক্ষক মন্ডলী',
                'child_menu_slug' => 'sikshk-mndlee',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-18 12:23:48',
                'updated_at' => '2024-03-18 12:23:48',
            ],
            [
                'menu_id' => 1,
                'submenu_id' => 3,
                'childmenu_name' => 'কর্মচারী ব্রিন্দ',
                'child_menu_slug' => 'krmcaree-brind',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-18 12:25:24',
                'updated_at' => '2024-03-18 12:25:24',
            ],
            [
                'menu_id' => 1,
                'submenu_id' => 3,
                'childmenu_name' => 'তথ্য প্রদানকারী কর্মকর্তা',
                'child_menu_slug' => 'tthz-prdankaree-krmkrta',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-18 12:26:13',
                'updated_at' => '2024-03-18 12:26:13',
            ],
            [
                'menu_id' => 1,
                'submenu_id' => 3,
                'childmenu_name' => 'অভিযোগ নিস্পত্তি কর্মকর্তা',
                'child_menu_slug' => 'ovizog-nisptti-krmkrta',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-18 12:48:47',
                'updated_at' => '2024-03-18 12:48:47',
            ],
            [
                'menu_id' => 1,
                'submenu_id' => 3,
                'childmenu_name' => 'ফোকাল পয়েন্ট কর্মকর্তা',
                'child_menu_slug' => 'fokal-pyent-krmkrta',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-18 12:50:08',
                'updated_at' => '2024-03-18 12:50:08',
            ],
            [
                'menu_id' => 2,
                'submenu_id' => 4,
                'childmenu_name' => 'পাট্যক্রমের স্তর সমুহ',
                'child_menu_slug' => 'patzkrmer-str-smuh',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 11:25:26',
                'updated_at' => '2024-03-20 11:25:26',
            ],
            [
                'menu_id' => 2,
                'submenu_id' => 4,
                'childmenu_name' => 'বিভাগ ও বিষয় সমুহ',
                'child_menu_slug' => 'bivag-oo-bishy-smuh',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 11:26:10',
                'updated_at' => '2024-03-20 11:26:10',
            ],
            [
                'menu_id' => 2,
                'submenu_id' => 4,
                'childmenu_name' => 'পাঠ কার্যক্রমের সময় সীমা',
                'child_menu_slug' => 'path-karzkrmer-smy-seema',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 11:27:03',
                'updated_at' => '2024-03-20 11:27:03',
            ],
            [
                'menu_id' => 2,
                'submenu_id' => 5,
                'childmenu_name' => 'ভর্তির বিজ্ঞপ্তি / নোটিশ',
                'child_menu_slug' => 'vrtir-bijngpti-notis',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 11:28:30',
                'updated_at' => '2024-03-20 11:28:30',
            ],
            [
                'menu_id' => 2,
                'submenu_id' => 5,
                'childmenu_name' => 'ভর্তির আবেদন ফরম',
                'child_menu_slug' => 'vrtir-abedn-frm',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 11:29:29',
                'updated_at' => '2024-03-20 11:29:29',
            ],
            [
                'menu_id' => 2,
                'submenu_id' => 5,
                'childmenu_name' => '্ভর্তি পরিক্ষা',
                'child_menu_slug' => 'vrti-priksha',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 11:29:52',
                'updated_at' => '2024-03-20 11:29:52',
            ],
            [
                'menu_id' => 2,
                'submenu_id' => 5,
                'childmenu_name' => 'ভর্তি পরীক্ষার ফলাফল',
                'child_menu_slug' => 'vrti-preekshar-flafl',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 11:30:40',
                'updated_at' => '2024-03-20 11:30:40',
            ],
            [
                'menu_id' => 2,
                'submenu_id' => 6,
                'childmenu_name' => 'পরীক্ষার নোটিশ',
                'child_menu_slug' => 'preekshar-notis',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 11:31:48',
                'updated_at' => '2024-03-20 11:31:48',
            ],
            [
                'menu_id' => 2,
                'submenu_id' => 6,
                'childmenu_name' => 'পরীক্ষার ফরম পূরণ',
                'child_menu_slug' => 'preekshar-frm-puurn',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 11:32:50',
                'updated_at' => '2024-03-20 11:32:50',
            ],
            [
                'menu_id' => 2,
                'submenu_id' => 6,
                'childmenu_name' => 'পরীক্ষার সম্ভাব্য তারিখ',
                'child_menu_slug' => 'preekshar-smvabz-tarikh',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 11:33:34',
                'updated_at' => '2024-03-20 11:33:34',
            ],
            [
                'menu_id' => 2,
                'submenu_id' => 7,
                'childmenu_name' => 'ফলাফল সংক্রান্ত নোটিস',
                'child_menu_slug' => 'flafl-sngkrant-notis',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 11:35:31',
                'updated_at' => '2024-03-20 11:35:31',
            ],
            [
                'menu_id' => 2,
                'submenu_id' => 7,
                'childmenu_name' => 'এইচএসসির ফলাফল',
                'child_menu_slug' => 'eicessir-flafl',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 11:36:35',
                'updated_at' => '2024-03-20 11:36:35',
            ],
            [
                'menu_id' => 2,
                'submenu_id' => 7,
                'childmenu_name' => 'ডিগ্রীর ফলাফল',
                'child_menu_slug' => 'digreer-flafl',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 11:37:24',
                'updated_at' => '2024-03-20 11:37:24',
            ],
            [
                'menu_id' => 2,
                'submenu_id' => 7,
                'childmenu_name' => 'অনার্সের ফলাফল',
                'child_menu_slug' => 'onarser-flafl',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 11:38:22',
                'updated_at' => '2024-03-20 11:38:22',
            ],
            [
                'menu_id' => 2,
                'submenu_id' => 7,
                'childmenu_name' => 'মাস্টার্সের ফলাফল',
                'child_menu_slug' => 'mastarser-flafl',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 11:39:14',
                'updated_at' => '2024-03-20 11:39:14',
            ],
            [
                'menu_id' => 3,
                'submenu_id' => 8,
                'childmenu_name' => 'লাইব্রেরি',
                'child_menu_slug' => 'laibreri',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 12:00:18',
                'updated_at' => '2024-03-20 12:00:18',
            ],
            [
                'menu_id' => 3,
                'submenu_id' => 8,
                'childmenu_name' => 'বিজ্ঞান ক্লাব',
                'child_menu_slug' => 'bijngan-klab',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 12:00:38',
                'updated_at' => '2024-03-20 12:00:38',
            ],
            [
                'menu_id' => 3,
                'submenu_id' => 8,
                'childmenu_name' => 'ডিবেটিং ক্লাব',
                'child_menu_slug' => 'dibeting-klab',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 12:01:06',
                'updated_at' => '2024-03-20 12:01:06',
            ],
            [
                'menu_id' => 3,
                'submenu_id' => 8,
                'childmenu_name' => 'ভ্রয়ামাগার',
                'child_menu_slug' => 'bzayamagar',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 12:01:43',
                'updated_at' => '2024-03-20 12:01:43',
            ],
            [
                'menu_id' => 3,
                'submenu_id' => 8,
                'childmenu_name' => 'ক্রীড়াঙ্গন',
                'child_menu_slug' => 'kreerangon',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 12:02:34',
                'updated_at' => '2024-03-20 12:02:34',
            ],
            [
                'menu_id' => 3,
                'submenu_id' => 9,
                'childmenu_name' => 'বিএনসিসি',
                'child_menu_slug' => 'biensisi',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 12:04:27',
                'updated_at' => '2024-03-20 12:04:27',
            ],
            [
                'menu_id' => 3,
                'submenu_id' => 9,
                'childmenu_name' => 'রোভার্স এন্ড স্কাঊটস',
                'child_menu_slug' => 'rovars-end-skauuts',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 12:05:29',
                'updated_at' => '2024-03-20 12:05:29',
            ],
            [
                'menu_id' => 3,
                'submenu_id' => 9,
                'childmenu_name' => 'রেড ক্রিসেন্ট',
                'child_menu_slug' => 'red-krisent',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 12:06:13',
                'updated_at' => '2024-03-20 12:06:13',
            ],
            [
                'menu_id' => 3,
                'submenu_id' => 9,
                'childmenu_name' => 'রেঞ্জার',
                'child_menu_slug' => 'renjar',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 12:06:31',
                'updated_at' => '2024-03-20 12:06:31',
            ],
            [
                'menu_id' => 3,
                'submenu_id' => 9,
                'childmenu_name' => 'আইসিটি ট্রেনিং',
                'child_menu_slug' => 'aisiti-trening',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 12:06:57',
                'updated_at' => '2024-03-20 12:06:57',
            ],
            [
                'menu_id' => 3,
                'submenu_id' => 10,
                'childmenu_name' => 'বাঁধন',
                'child_menu_slug' => 'banndhn',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 12:08:11',
                'updated_at' => '2024-03-20 12:08:11',
            ],
            [
                'menu_id' => 3,
                'submenu_id' => 10,
                'childmenu_name' => 'সংস্কৃতি কেন্দ্র',
                'child_menu_slug' => 'sngskrriti-kendr',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 12:09:39',
                'updated_at' => '2024-03-20 12:09:39',
            ],
            [
                'menu_id' => 3,
                'submenu_id' => 10,
                'childmenu_name' => 'রিপোর্টাস ইউনিটি',
                'child_menu_slug' => 'riportas-iuniti',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 12:10:37',
                'updated_at' => '2024-03-20 12:10:37',
            ],
            [
                'menu_id' => 3,
                'submenu_id' => 10,
                'childmenu_name' => 'থিয়েটার ও নাট্য সংগঠন',
                'child_menu_slug' => 'thiyetar-oo-natz-snggthn',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 12:11:31',
                'updated_at' => '2024-03-20 12:11:31',
            ],
            [
                'menu_id' => 3,
                'submenu_id' => 11,
                'childmenu_name' => 'হোস্টেল ১',
                'child_menu_slug' => 'hostel-1',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 12:12:50',
                'updated_at' => '2024-03-20 12:12:50',
            ],
            [
                'menu_id' => 3,
                'submenu_id' => 11,
                'childmenu_name' => 'হোস্টেল ২',
                'child_menu_slug' => 'hostel-2',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 12:13:06',
                'updated_at' => '2024-03-20 12:13:06',
            ],
            [
                'menu_id' => 3,
                'submenu_id' => 11,
                'childmenu_name' => 'হোস্টেল ৩',
                'child_menu_slug' => 'hostel-3',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 12:13:21',
                'updated_at' => '2024-03-20 12:13:21',
            ],
            [
                'menu_id' => 3,
                'submenu_id' => 11,
                'childmenu_name' => 'হোস্টেল ৪',
                'child_menu_slug' => 'hostel-4',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 12:13:37',
                'updated_at' => '2024-03-20 12:13:37',
            ],
            [
                'menu_id' => 4,
                'submenu_id' => 12,
                'childmenu_name' => 'অনলাইন পেমেন্ট পোটাল',
                'child_menu_slug' => 'onlain-pement-potal',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 12:15:41',
                'updated_at' => '2024-03-20 12:15:41',
            ],
            [
                'menu_id' => 4,
                'submenu_id' => 12,
                'childmenu_name' => 'ই - পেমেন্ট লগইন',
                'child_menu_slug' => 'i-pement-lgin',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 12:16:17',
                'updated_at' => '2024-03-20 12:16:17',
            ],
            [
                'menu_id' => 4,
                'submenu_id' => 12,
                'childmenu_name' => 'প্রাথমিক আবেদন ফি',
                'child_menu_slug' => 'prathmik-abedn-fi',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 12:17:03',
                'updated_at' => '2024-03-20 12:17:03',
            ],
            [
                'menu_id' => 4,
                'submenu_id' => 13,
                'childmenu_name' => 'এডমিশন পে স্লিপ',
                'child_menu_slug' => 'edmisn-pe-slip',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 12:17:42',
                'updated_at' => '2024-03-20 12:17:42',
            ],
            [
                'menu_id' => 4,
                'submenu_id' => 13,
                'childmenu_name' => 'প্রাথমিক আবেদন পে স্লিপ',
                'child_menu_slug' => 'prathmik-abedn-pe-slip',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 12:18:35',
                'updated_at' => '2024-03-20 12:18:35',
            ],
            [
                'menu_id' => 4,
                'submenu_id' => 14,
                'childmenu_name' => 'এ্যাডেমিক রেজাল্ট',
                'child_menu_slug' => 'ekademik-rejalt',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 12:22:35',
                'updated_at' => '2024-03-20 12:22:35',
            ],
            [
                'menu_id' => 4,
                'submenu_id' => 14,
                'childmenu_name' => 'এডুকেশন বোর্ড রেজাল্ট',
                'child_menu_slug' => 'edukesn-bord-rejalt',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 12:23:26',
                'updated_at' => '2024-03-20 12:23:26',
            ],
            [
                'menu_id' => 4,
                'submenu_id' => 14,
                'childmenu_name' => 'ন্যাশনাল ইউনির্ভাসিটি রেজাল্ট',
                'child_menu_slug' => 'nzasnal-iunirvasiti-rejalt',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 12:27:49',
                'updated_at' => '2024-03-20 12:27:49',
            ],
            [
                'menu_id' => 4,
                'submenu_id' => 15,
                'childmenu_name' => 'ডাউনলোড এ্যাপস',
                'child_menu_slug' => 'daunlod-ezaps',
                'child_menu_desc' => NULL,
                'upload' => '',
                'child_menu_status' => 1,
                'dept_id' => 0,
                'created_at' => '2024-03-20 12:28:43',
                'updated_at' => '2024-03-20 12:28:43',
            ],


            // Add more child menu data here as needed


        ]);
    }
}
